### ISSUE TITLE
After updating today, I get an error in class-mainwp-child.php

### ISSUE THREAD

**Issue by rgoodie** [mainwp/mainwp-child#10]
I updated today via `wp plugin update --all`. Afterwhich, users began getting the White Screen. Apache logs started showing the following issue. 

> Can't use function return value in write context in `/var/www/html/wp-content/plugins/mainwp-child/class/class-mainwp-child.php`

I then removed the `mainwp-child` folder and tried to install again. I got the same result. 

Running RHEL 7.2 w/ PHP 5.4.16

**Comment by ruben-** [comment]
This has been fixed, there was an issue with PHP5.4 and below. Apologies on that. Fixed in commit acdde0a28b69c445fbf5e00e2b4bcbd7b08f5fec
