### ISSUE TITLE
Problem with reporting plugin activation state on multisite

### ISSUE THREAD

**Issue by ktosiek** [mainwp/mainwp-child#11]
Hi!
I have a multisite child.
I've enabled MainWP Child plugin only on the main site.
I've enable BackWpUp for all sites.
The "Server Information" shows BackWpUp as Active, but even after syncing it still shows up as Inactive in the MainWP Dashboard.
I was expecting it to show up as Active in the MainWP Dashboard, and to be able to manage BackWpUp jobs through the dashboard extension.

**Comment by bogdan-mainwp** [comment]
Please note that the MainWP Plugin is not designed for WP Multisite. We haven't fully tested it on Multisites.

**Comment by ktosiek** [comment]
Do you plan on supporting multisite installations any time soon? Is there anything I can do to help with this?

I'm looking for a self-hosted, extensible WP central management system to use with client's installs. So far MainWP looks great, but I would need it to work with multisite installs at least for managing updates and backups.

**Comment by ktosiek** [comment]
It looks like using is_plugin_active would be more precise than what's done now in `get_all_plugins_int`: https://github.com/mainwp/mainwp-child/blob/aaf70d27afc59656a98e31bbee550db629d39091/class/class-mainwp-child.php#L4196 - I've tried using it on a multisite install, and the results are more precise.

Would you accept a PR changing that line to use `is_plugin_active( $pluginslug )`?

**Comment by bogdan-mainwp** [comment]
Thanks for reporting this. We do not plan to add support for multisite in the near future. Please feel free to submit pull requests for anything that you see that can be improved. Our dev team will review that respond as soon as possible.
