### ISSUE TITLE
index.php with die() return a code 200 instead of 4xx

### ISSUE THREAD

**Issue by BoiteAWeb** [mainwp/mainwp-child#13]
Hello, Julio from SecuPress.

A customer discovered that mainwp-child plugin was a guilty creator of an index.php file into /uploads/ which only contains a die().
https://github.com/mainwp/mainwp-child/blob/master/class/class-mainwp-security.php#L56
Unfortunately, this returns a http code 200 instead of 4xx (403?).

So i propose you to use a proper php header 403 return like
`header($_SERVER['HTTP_PROTOCOL'] . ' 403 Forbidden' );`
`die( '403 Fordibben' );`

Thank you

**Comment by bogdan-mainwp** [comment]
Julio, thanks for reporting this. I will notify the dev team right away.

**Comment by BoiteAWeb** [comment]
You're welcome.

**Comment by bogdan-mainwp** [comment]
The dev team reports that this has been completed. I will go ahead and close the issue.
