### ISSUE TITLE
Security Scan misleading

### ISSUE THREAD

**Issue by bitstarr** [mainwp/mainwp-child#14]
Hi,
I really like MainWP, it's a big help for managin many WP instances.
The checks for hiding wp_generator, RSD and WLW a bit problematic.

I use a code like the following in many projects:
```
function sanitize_wordpress() {
    remove_action( 'wp_head', 'wp_generator' );
    remove_action( 'wp_head', 'wlwmanifest_link' );
    remove_action( 'wp_head', 'rsd_link' );
}
add_action( 'get_header', 'sanitize_wordpress' );
```

But the scan says that they are not hidden.
Can you get the scan more precise?

Thanks!

**Comment by bogdan-mainwp** [comment]
The issue is being under the dev team review

**Comment by bogdan-mainwp** [comment]
Problem is fixed in the `getSecurityStats()` - class/class-mainwp-child.php
