### ISSUE TITLE
[FEATURE REQUEST] Make it possible to show "Contact support" for editors?

### ISSUE THREAD

**Issue by Nordis** [mainwp/mainwp-child#17]
For clients, I usually make them "Editor" so they can't mess things up. They would really need the "Contact support" option.

So please make it possible to show that for editors as well. At least as an option.

**Comment by bogdan-mainwp** [comment]
This feature request has been submitted to our Trello board for the Branding extension. For any future feature request, please check the https://mainwp.com/mainwp-roadmaps/ page.
