### ISSUE TITLE
PHP 7.2 Deprecated Notice

### ISSUE THREAD

**Issue by EntrepreneurAJ** [mainwp/mainwp-child#18]
I have enabled debugging to look into a seperate issue and the following error has appeared.

`Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /home/startuppeople/public_html/wp-content/plugins/mainwp-child/mainwp-child.php on line 39`

My setup is running php 7.2

**Comment by afragen** [comment]
+1
