### ISSUE TITLE
Error in SQL Syntax related to MySQL v8.0

### ISSUE THREAD

**Issue by DevWael** [mainwp/mainwp-child#25]
Hello,
i have installed a WordPress installation with the latest version on my server with PHP v7.2 and MySQL v8.0
i have an error in the plugin MainWP Child in the following file
`mainwp-child/class/class-mainwp-child-server-information.php`
at line `1157`

and the error says `SHOW VARIABLES LIKE "version"`

the original line says `return $wpdb->get_var( 'SHOW VARIABLES LIKE "version"', 1 );`
I have tried a solution to change the `"` to `'`
`return $wpdb->get_var( "SHOW VARIABLES LIKE 'version'", 1 );`

and it worked.
but I don't know what is the impact of this change.
so anyone can help?

Thanks in advance

**Comment by bogdan-mainwp** [comment]
Hi @DevWael,

This problem is fixed in the `getMySQLVersion()` function - class/class-mainwp-child-server-information.php

Thanks for reporting it.
