### ISSUE TITLE
Missing php version check before plugin update

### ISSUE THREAD

**Issue by sallec** [mainwp/mainwp-child#252]
MainWP does not check if site is running minimum php version required by the plugin.
It allows to update plugin which Wordpress does not allow to be updated.
After updating such plugin site is broken.

Steps to reproduce:
1. Install Wordpress with php 7.0
2. Install plugin СрбТрансЛатин version 2.0.2
3. Check plugins for update from MainWP, you will see that you can update this plugin to version 2.4 but if you do that site will be broken (because new version of the plugin requires PHP 7.2)

MainWP should not update plugins if minimum PHP version is not satisfied.

**Comment by bogdan-mainwp** [comment]
Hi @sallec,

thanks for reaching out and reporting this. 

I will check with our dev team about this problem and see what it takes to add this functionality.

Allow us some time please.

**Comment by bogdan-mainwp** [comment]
Hi @sallec, 

thanks one more time for your patience.

I talked to the dev team and they will add this functionality in the next release. Starting from the next version, in case of PHP version incompatibility detected by WP, MainWP will also prevent updates.

**Comment by sallec** [comment]
Hi @bogdan-mainwp ,

that's great news.
I just started exploring MainWP capabilities, looks like a great software.
Keep up with a good work.
Thanks.

**Comment by bogdan-mainwp** [comment]
Thanks, @sallec,

The dev team made the update. 

Do you want to try the pre-release version or you prefer to wait for the official update?

**Comment by sallec** [comment]
Hey @bogdan-mainwp ,

Sorry, i didn't saw this message in time. I'm interested in testing pre-release versions, I know how to debug, just tell me how to install it and what should I test.

**Comment by bogdan-mainwp** [comment]
Included since 4.1.4
