### ISSUE TITLE
Abandoned Plugins not detected

### ISSUE THREAD

**Issue by sallec** [mainwp/mainwp-child#253]
In MainWP plugin, "Abandoned plugins" shows none, but Wordfence plugin on a child site reports several plugins removed from wordpress.org.

Output from Wordfence scan:

The Plugin "MyPuzzle - Sudoku" has been removed from wordpress.org.
Type: Plugin Removed

The Plugin "Puzzle Game Widgets" has been removed from wordpress.org.
Type: Plugin Removed

1. Link for the first plugin from the plugins page as "Visit plugin site"
http://blog.mypuzzle.org/sudoku-for-wordpress/
(website does not work, probably deleted, i don't know if this plugin was originally downloaded from wordpress.org or not)

2. Link for the second plugin from the wordpress.org site
https://wordpress.org/plugins/puzzle-game-widgets/
(plugin closed, not available for downloads due Guideline Violations, this link is removed from the plugins page)

MainWP should display this plugins as removed/abandoned/unsafe if possible.
("Visit plugins site" link from Wordpress Plugins page could be checked to see if it exists or in case of a link to wordpress.org somehow check the state of that plugin)

**Comment by sallec** [comment]
Another example of this issue, MainWP dashboard does not report Abandoned plugins but on one child site Wordpress reports:

The Plugin "NextGEN Gallery Voting" appears to be abandoned (updated December 17, 2014, tested to WP 4.0.32).
Type: Plugin Abandoned
Issue Found December 20, 2020 4:44 am
Medium
Ignore

    Details

    Plugin Name: NextGEN Gallery Voting
    Current Plugin Version: 2.7.6
    Last Updated: December 17, 2014
    Details: It was last updated 6 years ago and tested up to WordPress 4.0.32. Plugins can be removed from wordpress.org for various reasons. This can include benign issues like a plugin author discontinuing development or moving the plugin distribution to their own site, but some might also be due to security issues. In any case, future updates may or may not be available, so it is worth investigating the cause and deciding whether to temporarily or permanently replace or remove the plugin. Get more information.
    Plugin URL: http://shauno.co.za/wordpress/nextgen-gallery-voting/
    Repository URL: https://wordpress.org/plugins/nextgen-gallery-voting

This plugin is still on Wordpress.org site but hasn't been updated for 6 years, it should be reported as Abandoned plugin.

**Comment by bogdan-mainwp** [comment]
Hi @sallec,

Thanks for this report.

Our dev will check this as soon as possible.

Thanks

**Comment by bogdan-mainwp** [comment]
Hi @sallec ,

we checked this and in case a plugin has been removed from the WP.org repository, the WP API returns `Plugin not found`, which is the same response as we would get in case of any plugin that has never been hosted on WP.org.

This means that we can't accurately detect plugins that have been removed from WP.org and notify users. Basically, this would create a lot of false positives.

Thanks

**Comment by sallec** [comment]
Hi @bogdan-mainwp ,

what if MainWP checks all plugins that it finds installs on the site and creates a snapshot of the state for every plugin, then recheck from time to time and compare status to see if something changed.

Examples:
1. At the time when MainWP Child plugin is installed some X plugin was detected on wordpress.org. Then every day, wordpress.org is rechecked for plugin X, and if WP API returns for example "Plugin not found" that would mean that plugin was deleted from wordpress.org and can be considered as Abandoned.
2. Using the same principle if plugin Y was updated 1 month ago when MainWP Child was installed, and after six months data returned from wordpress.org suggests that plugin has not been updated for 6 more months, this can also mean that plugin was Abandoned (or whatever time period you consider for plugin to be Abandoned).
3. If plugin hasn't been installed from wordpress.org, MainWP cant plugin url that it finds and check if url stops working (I have some examples that the plugin url is not working anymore). This also is suggesting that plugin could be Abandoned (or website could be down for that moment but anyways this will bring user attention to recheck this plugin state).

This are just few quick ideas you maght consider if you want to improve Abandoned plugins functionality.

Thanks.

**Comment by bogdan-mainwp** [comment]
We have decided to reject this suggestion. Our dev team decided that saving plugin status in the site database is not a good practice. We believe it's better to always get fresh data from WP API.
