### ISSUE TITLE
WP CLI commands to allow remote activation

### ISSUE THREAD

**Issue by planetahuevo** [mainwp/mainwp-child#285]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to add a site into mainwp securely using ssh and command line. 
We can add the plugin on the child site, but we cannot get the security key. 

**Describe the solution you'd like**
Using a wp cli command, we could "activate the security key option" and get the key too. 

For example: 
wp mainwpchild securitykey --activate
That will return the key if already activated or activate it and then return the security key. 

With that, we could ssh into our mainwp installation and use wp cli to add the new site including the security key.

Other wp cli commands could be added, for example to reset the database options of mainwp chlid plugin (which could fix a lot problems with connections) but that could be for another moment. :) 

What do you think?

**Comment by bogdan-mainwp** [comment]
Hi @planetahuevo,

please feel free to join the [MainWP Community](https://meta.mainwp.com/) and post your feature suggestion to the Features section.
