### ISSUE TITLE
MainWP hides error messages

### ISSUE THREAD

**Issue by d-damien** [mainwp/mainwp-child#287]
**Describe the bug**
It appears MainWP hides certain error messages, which can make debugging quite complicated. The result is that you just see the usual Wordpress critical error panel, but without any specific indication. Another important point is that nothing is logged : no 500 error shows in Apache logs.

**To Reproduce**
It's not always reproducible unfortunately, but the most common unlogged problem is the "out of memory" error. Install a well-known memory greedy Wordpress plugin, with MainWP Child activated, and when it crashes, you will (probably) see the problem. It doesn't tell you which plugin is at fault.

The plugins with which I've had that kind of encounters are WooCommerce with Jetpack & YoastSEO.

**Expected behavior**
Let errors be logged. And displayed if `WP_DEBUG` is `true`.

**Server**
Debian 9.13 with Apache 2.4 and PHP 7.4 FPM.
`memory_limit` is 256 MB, which is enough for a large majority of websites.

Thanks

**Comment by bogdan-mainwp** [comment]
Hi @d-damien, 

do you have Security Issues fixes applied for the child site in your MainWP Dashboard?

**Comment by bogdan-mainwp** [comment]
@d-damien if you still experience this problem, feel free to reach out to us via helpdesk ticket.
