### ISSUE TITLE
raw HTML displayed when plugin is first activated

### ISSUE THREAD

**Issue by nosilver4u** [mainwp/mainwp-child#348]
When the child plugin is first activated, we get a lovely warning/attention dialog. Within the text of that warning, "NOW" is supposed to be in bold, but the 'strong' tags seem to be HTML-encoded, so they are displayed instead of making **NOW** bold.

**To Reproduce**
1. Activate the plugin
2. Read the warning message that comes up, and you'll see the HTML strong tags displayed

**Expected behavior**
NOW should be bold!

**Screenshots**
![Screen Shot 2023-02-22 at 2 55 24 PM](https://user-images.githubusercontent.com/6015678/220768908-0bc35b62-e186-4bb4-aa80-09e5915b160b.png)

**Comment by bogdan-mainwp** [comment]
Hi @nosilver4u,

Thanks for the report.
This problem is fixed in the version 4.4.0.1
