### ISSUE TITLE
ENH: Please add wp-cli support to return or register a private key when the main wp child plugin is activated 

### ISSUE THREAD

**Issue by elindydotcom** [mainwp/mainwp-child#399]
**Is your feature request related to a problem? Please describe.**
When deploying a new site using wp-cli, we want to be able to install the mainwp child plugin in a secure manner which means using wp-cli to activate the plugin with an option to provide or obtain the private connection string.

**Describe the solution you'd like**
One of two options:
1. Create a wp-cli command that installs the mainwp child plugin with the 'secure' option enabled and return the security string.  We can then use wp-cli on the mainwp plugin to register the site using that string.
2. Create a wp-cli command that installs the mainwp child plugin with a security string that we provide. We can then use wp-cli on the mainwp plugin to register the site using that string.

Either way, using wp-cli to just install and activate the mainwp child plugin right now would leave the site open to attacks if the second step to register the site with the MAINWP plugin failed for any reason.  

I realize that there is a chicken-and-egg problem here that needs to be solved because you can't invoke a custom wp-cli command until the mainwp child plugin is enabled.  BUT, maybe an alternative is that an try in wp-config.php forces mainwp child to activate in secure mode instead of being wide open to the first connection that show up.

**Describe alternatives you've considered**
Forking the mainwp child plugin and adding the wp-cli command ourselves.

**Additional context**
Using wp-cli to install the mainwp child plugin right now risks leaving a site open to attack.

**Comment by kwcjr** [comment]
@elindydotcom We apologize for the tardy response on this topic however, we usually take Feedback/Issues submissions either by our [Community Site](https://manager.mainwp.com) & or [Private Support Tickets](https://mainwp.com/my-account/get-support). If you could copy and paste your request onto our Feedback Board it will be available for the rest of the community to vote on it as a new feature. 

In the meantime - MainWP is indeed Open-Source & you do have the right to either Fork this repository or you may contribute to the community by requesting a Pull Request & having your additions added to Core. The choice is all yours. :) 

I am going to close this thread as it will be picked up on the feedback site.
