### ISSUE TITLE
$this->archiver->getFromName('clone/config.txt'); goes into infinite loop

### ISSUE THREAD

**Issue by ingomarent** [mainwp/mainwp-child#4]
Hi,

On File 
MainWPCloneInstall.class.php
Line 562

Under HipHop VM 3.7.2 
Dont know if it happens with PHP Versions too.

**Comment by bogdan-mainwp** [comment]
The dev team reports that this issue has been fixed in one of the previous versions. 
If the issue still persists for you, please [open a helpdesk ticket](https://mainwp.com/support/) so the dev team can review this.
