### ISSUE TITLE
Child websites send empty users data

### ISSUE THREAD

**Issue by cristianorevil** [mainwp/mainwp-child#433]
After last update the child website send to the dashboard the "users" filed empty like:

   "users":"[]",

**Comment by bogdan-mainwp** [comment]
HI @cristianorevil, I see that you posted the same question on in the Dashboard plugin repo too, so I will close this one.
As I suggested in the [Issue 723](https://github.com/mainwp/mainwp/issues/723), it is needed to enable the "Optimize data loading" option in the MainWP > Settings > Advanced Options page
