### ISSUE TITLE
White label

### ISSUE THREAD

**Issue by AdrianoCahete** [mainwp/mainwp-child#8]
Can i white labeling this plugin?

**Comment by dennisdornon** [comment]
You can use the [MainWP Branding Extension](https://mainwp.com/extension/branding/) to white label the Child plugin.

**Comment by AdrianoCahete** [comment]
Hi Dennis, thanks for the answer. I didn't install MainWP yet, so i don't see how Child plugin appears on client's WP.

Since it's a WP plugin (and open source, thanks for that!), can i maintain the child plugin with my edits? It's a license question, in fact.

Don't get me wrong, i want to pay for lifetime membership soon (when my main currency is less than 4x the dollar, to be more specific), but i can't do now.

**Comment by AdrianoCahete** [comment]
Just for update: I installed in some clients and find the best approach is to hide completely from final user. Using css to hide from menu and some lines in config to hide from plugin list.

Regardless of this, i still consider to pay for a lifetime membership.
